# 单库+分表
spring:
  shardingsphere:
    datasource:
      names: tax
      # datasoure名称
      tax:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.1.1.151:3306/shardingJdbc-master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        password: test@DB
        type: com.alibaba.druid.pool.DruidDataSource
        username: test

    sharding:
      tables:
        tax_report_data_storage:
          actual-data-nodes: tax.tax_report_data_storage_$->{2019..2020}
          #          key-generator:
          #            column: id
          #            props:
          #              worker:
          #                id: 123
          #            type: UUID
          # 分表策略
          table-strategy:
            standard:
              sharding-column: task_id
              # 分表策略算法
              precise-algorithm-class-name: com.dxhy.shardingsphere.config.SeparateTablePreciseAlgorithm
    #            行表达式分片算法
    #            inline:
    #              sharding-column: task_id
    #              algorithm-expression: tax_report_data_storage_$->{task_id % 2}
    props:
      sql:
        show: true