# 分库+分表

spring:
  shardingsphere:
    props:
      sql:
        show: true
    #    masterslave:
    #      name: taxtest
    #      master-data-source-name: tax
    #      slave-data-source-names: tax1
    datasource:
      names: tax0,tax1
      # datasoure名称
      tax0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.1.1.151:3306/shardingJdbc-master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        password: test@DB
        type: com.alibaba.druid.pool.DruidDataSource
        username: test
      tax1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.1.1.151:3306/shardingJdbc-salve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        password: test@DB
        type: com.alibaba.druid.pool.DruidDataSource
        username: test

    sharding:
      # 默认datasoure名称
      # default-data-source-name: tax0
      tables:
        tax_report_data_storage:
          database-strategy:
            standard:
              sharding-column: task_id
              precise-algorithm-class-name: com.dxhy.shardingsphere.config.SeparateDbPreciseAlgorithm
          actual-data-nodes: tax$->{0..1}.tax_report_data_storage_$->{2019..2020}
          #          key-generator:
          #            column: id
          #            props:
          #              worker:
          #                id: 123
          #            type: UUID
          # 分表策略
          table-strategy:
            standard:
              sharding-column: task_id
              precise-algorithm-class-name: com.dxhy.shardingsphere.config.SeparateTablePreciseAlgorithm