# 读写分离+分表

spring:
  shardingsphere:
    #    masterslave:
    #      name: taxtest
    #      master-data-source-name: tax
    #      slave-data-source-names: tax1
    datasource:
      names: tax,tax1
      # datasoure名称
      tax:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.1.1.151:3306/shardingJdbc-master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        password: test@DB
        type: com.alibaba.druid.pool.DruidDataSource
        username: test
      tax1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.1.1.151:3306/shardingJdbc-salve?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
        password: test@DB
        type: com.alibaba.druid.pool.DruidDataSource
        username: test

    sharding:
      master-slave-rules:
        taxtest:
          master-data-source-name: tax
          slave-data-source-names: tax1
      # 默认datasoure名称
      # default-data-source-name: tax
      tables:
        tax_report_data_storage:
          database-strategy:
            standard:
              sharding-column: task_id
                precise-algorithm-class-name: com.dxhy.shardingsphere.config.TaxTestPreciseAlgorithm
          actual-data-nodes: taxtest.tax_report_data_storage_$->{2019..2022}
          #          key-generator:
          #            column: id
          #            props:
          #              worker:
          #                id: 123
          #            type: UUID
          # 分表策略
          table-strategy:
            standard:
              sharding-column: task_id
              precise-algorithm-class-name: com.dxhy.shardingsphere.config.TaxTestPreciseAlgorithm
      default-database-strategy:
    props:
      sql:
        show: true